### ISSUE TITLE
MACHINA_FORUM_NAME

### ISSUE THREAD

**Issue by vincentporte** [gip-inclusion/itou-communaute-django#543]
Le `title` des pages de lacommunauté est `Accueil- Machina` au lieu de `Accueil - La communauté de l'inclusion`, `Documentation- Machina` etc

`base.html` contient le titre comme suit : `{% block title %}- {{ MACHINA_FORUM_NAME|default:"Forum" }}{% endblock %}`

`MACHINA_FORUM_NAME`  semble alimenté avec la valeur du projet django-machina et non celui de la communauté.

**Comment by francoisfreitag** [comment]
Bisecté à f81390f4bef63f4c2896180fcf25fabbb2302733
