### ISSUE TITLE
[NOTIFICATION] augmenter le détail des notifications mail

### ISSUE THREAD

**Issue by vincentporte** [gip-inclusion/itou-communaute-django#670]
# Email template
1. utiliser les blocs de contenus répétés Brevo
2. template disponible : 28
3. paramètres du template : 
```
from config.settings.base import DEFAULT_FROM_EMAIL
from lacommunaute.notification.emails import send_email
params={"first_name":"Antoine","email_object":"Bonne nouvelle, Antoine, ça bouge pour vous dans la communauté !", "email_thumbnail":"Vous avez 3 messages à découvrir sur la communauté de l'inclusion", "messages":[{"poster":"John", "action":"a répondu à 'Règles ARE'", "forum":"l'espace d'échanges", "url":"ww1.neuralia.co"},{"poster":"bob.martins", "action":"a posé une nouvelle question dans", "forum":"diagnostique de territoire", "url":"ww2.neuralia.co"},{"poster":"John", "action":"a répondu à 'Stage découverte'", "forum":"PMSPM", "url":"ww3.neuralia.co"}]}
contacts=[{"email":"vincent.porte@beta.gouv.fr"}]


send_email(
    to=[{"email": DEFAULT_FROM_EMAIL}],
    params=params,
    template_id=28,
    kind='notification_multi',
    bcc=contacts,
)
```

# Modèle
1. app `notification`
2. nouveau modèle `notification`
     * email_to_notify : EmailField
     * post : FK
     * kind : choicefield
     * delay : choicefield (0:asap, 1:daily …)
     * send_at : datetime
     * created_at : datetime

# Mapping des params
`poster` = `post.poster_display_name()`
`action` = combinaison de `kind` et de `post.topic.subject`
`forum` = `post.topic.forum.name`
`url` = `post.topic.get_absolute_url(with_fqdn=True)`

# Population du modèle
1. `topic.mails_to_notify()`
2. lors de la creation de chaque post
3. si `post = topic.first_post`, `delay=0`, sinon `delay=1`

# Collecte des notifications non envoyées
1. tache cron tous les 15 min pour récolter les notifis avec `delay==0`
2. tache cron quotidienne pour récolter les notifs avec `delay <=1`
3. ⚠️ désactiver les tâches cron d'envoi d'emails pour éviter les doubles envois
     * `send_notifs_when_first_reply`
     * `send_notifs_when_following_replies`

**Comment by calummackervoy** [comment]
@vincentporte je pense qu'il est implicite qu'on va envoyer des notifications pour tous les nouveaux messages; on va pas tenter tracer que le message a été lu ou non ?

On a discuté de la possibilité de modifier l'interface pour afficher les notifications non lues - ce qui implique qu'on suivra un champ `read` sur les notifications aussi normalement. On pourrait également reporter cet ajout à un prochain ticket afin de minimiser la portée de celle-ci ?

**Comment by calummackervoy** [comment]
> "action":"a posé une nouvelle question dans", "forum":"diagnostique de territoire"

@vincentporte j'ai bien compris que cet action correspond au `EmailSentTrackKind.PENDING_TOPIC` ? Ça veut dire qu'on va remplacer les mails du `send_notifs_on_unanswered_topics` avec cet mail aussi ?
